"""rename address

Revision ID: 611a77448a7c
Revises: 9640b53ac74c
Create Date: 2024-07-27 17:36:17.599483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611a77448a7c'
down_revision = '9640b53ac74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###